version: '2'
services:
  dnscrypt-proxy:
    restart: unless-stopped
    image: atemu12/dnscrypt-proxy-2
    container_name: dnscrypt-proxy
    ports:
      - "53:53/udp"
    #volumes:
    #  - ./config:/config
